# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-merge-conflict

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.0.2
    hooks:
      - id: golangci-lint
        args: ["--timeout=10m"]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/python-openapi/openapi-spec-validator
    rev: 0.7.1
    hooks:
      - id: openapi-spec-validator
        exclude: .*_config.yaml
  - repo: https://gitlab.wikimedia.org/repos/cloud/cicd/gitlab-ci
    rev: 029fc9585c2664f4d0332f926b18fa5b460d4305
    hooks:
      - id: check-openapi-version-bump
