openapi: 3.1.0
info:
  title: Toolforge builds API
  version: 0.0.3
servers:
  - url: "http://127.0.0.1:8000"
    description: "Local direct development server."
  - url: "https://127.0.0.1:3000/builds"
    description: "Lima-kilo development server."
  - url: "https://api.svc.tools.eqiad1.wikimedia.cloud:30003/builds"
    description: "Toolforge internal API gateway endpoint."
  - url: "https://api.svc.toolsbeta.eqiad1.wikimedia.cloud:30003/builds"
    description: "Toolforge beta internal API gateway endpoint."

.common:
  common_responses:
    bad-parameters: &bad-parameters
      description: Bad parameters passed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseMessages"
    unauthorized: &unauthorized
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseMessages"
    not-found: &not-found
      description: The latest build was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseMessages"
    internal-error: &internal-error
      description: An internal error happened
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseMessages"
    conflict: &conflict
      description: operation conflicts with the current state of a build(s)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseMessages"

paths:
  /v1/build:
    post:
      operationId: start
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/BuildParameters"
        required: true
      responses:
        "200":
          description: returns the newly created build information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartResponse"
        "400": *bad-parameters
        "401": *unauthorized
        "404": *not-found
        "500": *internal-error
      security:
        - key: []
      x-codegen-request-body-name: new_build
    get:
      operationId: list
      responses:
        "200":
          description: Returns the list of builds
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListResponse"
        "401": *unauthorized
        "500": *internal-error
      security:
        - key: []
  /tool/{toolname}/v1/build:
    post:
      operationId: startWithToolname
      parameters:
        - name: toolname
          in: path
          required: true
          description: Name of the tool
          schema:
            type: string
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/BuildParameters"
        required: true
      responses:
        "200":
          description: returns the newly created build information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartResponse"
        "400": *bad-parameters
        "401": *unauthorized
        "404": *not-found
        "500": *internal-error
      security:
        - key: []
      x-codegen-request-body-name: new_build
    get:
      operationId: listWithToolname
      parameters:
        - name: toolname
          in: path
          required: true
          description: Name of the tool
          schema:
            type: string
      responses:
        "200":
          description: Returns the list of builds
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListResponse"
        "401": *unauthorized
        "500": *internal-error
      security:
        - key: []
  /v1/build/latest:
    get:
      operationId: latest
      responses:
        "200":
          description: The latest build
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LatestResponse"
        "400": *bad-parameters
        "401": *unauthorized
        "404": *not-found
        "500": *internal-error
      security:
        - key: []
  /v1/build/{id}:
    get:
      operationId: get
      parameters:
        - name: id
          in: path
          description: Id of the build
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: The build was found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetResponse"
        "400": *bad-parameters
        "401": *unauthorized
        "404": *not-found
        "500": *internal-error
      security:
        - key: []
    delete:
      operationId: delete
      parameters:
        - name: id
          in: path
          description: Id of the build
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: The build was deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteResponse"
        "400": *bad-parameters
        "401": *unauthorized
        "404": *not-found
        "500": *internal-error
      security:
        - key: []
  /v1/build/{id}/cancel:
    put:
      operationId: cancel
      parameters:
        - name: id
          in: path
          description: Id of the build
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: The build was canceled
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CancelResponse"
        "400": *bad-parameters
        "401": *unauthorized
        "404": *not-found
        "409": *conflict
        "500": *internal-error
      security:
        - key: []
  /v1/clean:
    post:
      operationId: clean
      parameters: []
      responses:
        "200":
          description: Returns a summary of what was cleaned up.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CleanResponse"
        "401": *unauthorized
        "500": *internal-error
      security:
        - key: []
  /v1/build/{id}/logs:
    get:
      operationId: logs
      parameters:
        - name: id
          in: path
          description: Id of the build
          required: true
          schema:
            type: string
        - name: follow
          in: query
          description: Follow the logs
          required: false
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: |
            returns newline separated sequence of "#/components/schemas/BuildLog" or
            "#/component/schemas/InternalError" if there was an error after the
            streaming has started (as the http status code can't be changed)
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/BuildLog"
        "400": *bad-parameters
        "401": *unauthorized
        "404": *not-found
        "500": *internal-error
      security:
        - key: []
  /v1/quota:
    get:
      operationId: quota
      responses:
        "200":
          description: Returns the quota information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuotaResponse"
        "401": *unauthorized
        "500": *internal-error
      security: []
  /v1/metrics:
    get:
      operationId: metrics
      responses:
        "200":
          description: Returns the metrics of the service
          content:
            text/plain:
              schema:
                type: string
      security: []
  /v1/healthz:
    get:
      operationId: healthcheck
      responses:
        "200":
          description: Returns the health status of the service
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "503":
          description: Returned when the service is not ready
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
      security: []
  /openapi.json:
    get:
      operationId: openapi
      parameters: []
      responses:
        "200":
          description: returns the openapi definition
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    ResponseMessages:
      type: object
      description: |
        Lists of messages by priority, note that there will be a warning here when the endpoint is being deprecated
        with information on how to proceed to update it.
      properties:
        info:
          type: array
          items:
            type: string
        warning:
          type: array
          items:
            type: string
        error:
          type: array
          items:
            type: string
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - OK
            - ERROR
        messages:
          $ref: "#/components/schemas/ResponseMessages"
    StartResponse:
      type: object
      properties:
        messages:
          $ref: "#/components/schemas/ResponseMessages"
        new_build:
          $ref: "#/components/schemas/NewBuild"
    DeleteResponse:
      type: object
      properties:
        messages:
          $ref: "#/components/schemas/ResponseMessages"
        id:
          description: "Id of the deleted build"
          type: string
    ListResponse:
      type: object
      properties:
        messages:
          $ref: "#/components/schemas/ResponseMessages"
        builds:
          type: array
          items:
            $ref: "#/components/schemas/Build"
    LatestResponse:
      type: object
      properties:
        messages:
          $ref: "#/components/schemas/ResponseMessages"
        build:
          $ref: "#/components/schemas/Build"
    QuotaResponse:
      type: object
      properties:
        messages:
          $ref: "#/components/schemas/ResponseMessages"
        quota:
          $ref: "#/components/schemas/Quota"
    GetResponse:
      type: object
      properties:
        messages:
          $ref: "#/components/schemas/ResponseMessages"
        build:
          $ref: "#/components/schemas/Build"
    CancelResponse:
      type: object
      properties:
        messages:
          $ref: "#/components/schemas/ResponseMessages"
        id:
          description: "Id of the cancelled build"
          type: string
    CleanResponse:
      type: object
      properties:
        messages:
          $ref: "#/components/schemas/ResponseMessages"
    BuildLog:
      type: object
      properties:
        line:
          type: string
    NewBuild:
      type: object
      properties:
        name:
          type: string
        parameters:
          $ref: "#/components/schemas/BuildParameters"
    # TODO: remove this as it doesn't seem to be used
    principal:
      type: object
      properties:
        user:
          type: string
    Build:
      allOf:
        - $ref: "#/components/schemas/BuildCondition"
        - type: object
          properties:
            build_id:
              type: string
            start_time:
              type: string
            end_time:
              type: string
            parameters:
              $ref: "#/components/schemas/BuildParameters"
            destination_image:
              type: string
    BuildParameters:
      required:
        - source_url
      type: object
      properties:
        source_url:
          type: string
          description: |
            URL to the public git repository that contains the source code
            to build
        ref:
          type: string
          description: Source code reference to build (ex. a git branch name)
        envvars:
          type: object
          additionalProperties:
            type: string
          description: Environment variables and values to be set at build time
        image_name:
          type: string
          description: The name of the image to be built
    BuildCondition:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/BuildStatus"
        message:
          type: string
    BuildStatus:
      type: string
      enum:
        - BUILD_RUNNING
        - BUILD_SUCCESS
        - BUILD_FAILURE
        - BUILD_CANCELLED
        - BUILD_TIMEOUT
        - BUILD_UNKNOWN
    Quota:
      type: object
      properties:
        categories:
          type: array
          items:
            $ref: "#/components/schemas/QuotaCategory"
    QuotaCategory:
      type: object
      properties:
        name:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/QuotaCategoryItem"
    QuotaCategoryItem:
      type: object
      properties:
        name:
          type: string
        limit:
          type: string
        used:
          type: string
        available:
          type: string
        capacity:
          type: string

  securitySchemes:
    key:
      type: apiKey
      name: ssl-client-subject-dn
      in: header
