releases:
  - name: builds-api
    chart: ./chart/
    namespace: builds-api
    createNamespace: true
    values:
      - ./values/{{ .Environment.Name }}.yaml*

environments:
  tools: {}
  toolsbeta: {}
  local: {}
