---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.api.secretName }}"
  labels:
    name: "{{ .Values.api.secretName }}"
spec:
  dnsNames:
    - "builds-api.{{ .Release.Namespace }}.svc"
  secretName: "{{ .Values.api.secretName }}"
  revisionHistoryLimit: 1
  issuerRef:
    name: "{{ .Values.api.secretName }}"
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-api-gateway-server
  labels:
    name: "builds-api"
spec:
  commonName: builds-api.{{ .Release.Namespace }}.svc
  secretName: {{ .Release.Name }}-api-gateway-server
  usages:
    - server auth
  duration: "504h" # 21d
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef: {{ .Values.certificates.apiGatewayCa | toYaml | nindent 4 }}
