// Code generated by go-swagger; Manually edited

package main

import (
	"context"
	"fmt"
	"os"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime/middleware"
	log "github.com/sirupsen/logrus"
	"github.com/tektoncd/pipeline/pkg/client/clientset/versioned"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"

	"gitlab.wikimedia.org/repos/toolforge/toolforge-builds-api/gen/models"
	"gitlab.wikimedia.org/repos/toolforge/toolforge-builds-api/gen/restapi"
	"gitlab.wikimedia.org/repos/toolforge/toolforge-builds-api/gen/restapi/operations"
	"gitlab.wikimedia.org/repos/toolforge/toolforge-builds-api/internal"
)

// This file was generated by the swagger tool.

func main() {
	log.SetFormatter(&log.JSONFormatter{})

	if os.Getenv("DEBUG") == "true" {
		log.SetLevel(log.DebugLevel)
		log.Info("Starting in DEBUG mode")
	}

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewToolforgeBuildsAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer func() {
		err := server.Shutdown()
		if err != nil {
			log.Fatalln(err.Error())
		}
	}()

	if os.Getenv("PORT") != "" {
		val, err := strconv.Atoi(os.Getenv("PORT"))
		if err != nil {
			log.Fatalf("Bad port specified '%s'", os.Getenv("PORT"))
		}

		server.Port = val
	} else {
		server.Port = 8000
	}

	// Applies when the "ssl-client-subject-dn" header is set
	api.KeyAuth = func(token string) (*models.Principal, error) {
		user, err := internal.ValidateUser(token)
		if err == nil {
			prin := models.Principal{
				User: user,
			}
			return &prin, nil
		}
		log.Infof("Access attempt with incorrect auth: %s", token)
		return nil, errors.New(401, "incorrect auth")
	}

	addHandlers(api)

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}

func addHandlers(api *operations.ToolforgeBuildsAPI) {
	k8sConfig, err := rest.InClusterConfig()
	if err != nil {
		log.Fatalln(err.Error())
	}

	// creates the clientset
	clientset, err := kubernetes.NewForConfig(k8sConfig)
	if err != nil {
		log.Fatalln(err.Error())
	}
	// creates the tekton clientset
	tektonClientset, err := versioned.NewForConfig(k8sConfig)
	if err != nil {
		log.Fatalln(err.Error())
	}
	clients := internal.Clients{
		Tekton: tektonClientset,
		K8s:    clientset,
	}

	// Declare handlers
	api.HealthcheckHandler = operations.HealthcheckHandlerFunc(
		func(params operations.HealthcheckParams) middleware.Responder {
			_, err := clients.K8s.CoreV1().Pods(internal.BuildNamespace).List(context.TODO(), metav1.ListOptions{})
			if err != nil {
				return operations.NewHealthcheckServiceUnavailable().WithPayload(&models.HealthResponse{
					Message: fmt.Sprintf("Unable to contact the k8s API: %s", err),
					Status:  "ERROR",
				})
			}
			return operations.NewHealthcheckOK().WithPayload(&models.HealthResponse{
				Message: "All systems normal",
				Status:  "OK",
			})
		})

	// Handler for getting a build
	api.LogsHandler = operations.LogsHandlerFunc(
		func(params operations.LogsParams, principal *models.Principal) middleware.Responder {
			return internal.Logs(params.ID, &clients, internal.BuildNamespace, principal.User)
		})

}
