// Code generated by go-swagger; Manually edited

package main

import (
	"context"
	"fmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime/middleware"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/viper"
	"github.com/tektoncd/pipeline/pkg/client/clientset/versioned"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"

	"gitlab.wikimedia.org/repos/toolforge/toolforge-builds-api/gen/models"
	"gitlab.wikimedia.org/repos/toolforge/toolforge-builds-api/gen/restapi"
	"gitlab.wikimedia.org/repos/toolforge/toolforge-builds-api/gen/restapi/operations"
	"gitlab.wikimedia.org/repos/toolforge/toolforge-builds-api/internal"
)

// This file was generated by the swagger tool.

func main() {
	log.SetFormatter(&log.JSONFormatter{})

	viper.AutomaticEnv()
	viper.AllowEmptyEnv(true)
	viper.SetDefault("debug", false)
	viper.SetDefault("port", 8000)
	// note that the builder is the full ref for the image
	viper.SetDefault("builder", "tools-harbor.wmcloud.org/toolforge/heroku-builder-classic:22")
	viper.SetDefault("ok_builds_to_keep", 1)
	viper.SetDefault("failed_builds_to_keep", 2)
	if viper.GetBool("debug") {
		log.SetLevel(log.DebugLevel)
		log.Info("Starting in DEBUG mode")
	}

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewToolforgeBuildsAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer func() {
		err := server.Shutdown()
		if err != nil {
			log.Fatalln(err.Error())
		}
	}()

	server.Port = viper.GetInt("port")

	// Applies when the "ssl-client-subject-dn" header is set
	api.KeyAuth = func(token string) (*models.Principal, error) {
		user, err := internal.ValidateUser(token)
		if err == nil {
			prin := models.Principal{
				User: user,
			}
			return &prin, nil
		}
		log.Infof("Access attempt with incorrect auth: %s", token)
		return nil, errors.New(401, "incorrect auth")
	}

	harborRepository := viper.GetString("HARBOR_REPOSITORY")
	if harborRepository == "" {
		log.Fatalf("No HARBOR_REPOSITORY set, one is needed.")
	}
	buildCleanup := map[string]int{
		"okBuildsToKeep":     viper.GetInt("ok_builds_to_keep"),
		"failedBuildsToKeep": viper.GetInt("failed_builds_to_keep"),
	}
	config := Config{
		HarborRepository: harborRepository,
		Builder:          viper.GetString("builder"),
		BuildCleanup:     buildCleanup,
	}

	log.Infof("Using config: %v", config)
	addHandlers(api, config)

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}

type Config struct {
	HarborRepository string
	Builder          string
	BuildCleanup     map[string]int
}

func addHandlers(api *operations.ToolforgeBuildsAPI, config Config) {
	k8sConfig, err := rest.InClusterConfig()
	if err != nil {
		log.Fatalln(err.Error())
	}

	// creates the clientset
	clientset, err := kubernetes.NewForConfig(k8sConfig)
	if err != nil {
		log.Fatalln(err.Error())
	}
	// creates the tekton clientset
	tektonClientset, err := versioned.NewForConfig(k8sConfig)
	if err != nil {
		log.Fatalln(err.Error())
	}
	clients := internal.Clients{
		Tekton: tektonClientset,
		K8s:    clientset,
	}

	// Declare handlers
	api.HealthcheckHandler = operations.HealthcheckHandlerFunc(
		func(params operations.HealthcheckParams) middleware.Responder {
			_, err := clients.K8s.CoreV1().Pods(internal.BuildNamespace).List(
				context.TODO(),
				metav1.ListOptions{
					Limit: 1,
				},
			)
			if err != nil {
				return operations.NewHealthcheckServiceUnavailable().WithPayload(&models.HealthResponse{
					Message: fmt.Sprintf("Unable to contact the k8s API: %s", err),
					Status:  "ERROR",
				})
			}
			return operations.NewHealthcheckOK().WithPayload(&models.HealthResponse{
				Message: "All systems normal",
				Status:  "OK",
			})
		})

	// Handler for getting a build logs
	api.LogsHandler = operations.LogsHandlerFunc(
		func(params operations.LogsParams, principal *models.Principal) middleware.Responder {
			return internal.Logs(params.ID, &clients, internal.BuildNamespace, principal.User)
		})

	// Handler for getting a build logs
	api.StartHandler = operations.StartHandlerFunc(
		func(params operations.StartParams, principal *models.Principal) middleware.Responder {
			return internal.Start(
				*params.NewBuild.SourceURL,
				params.NewBuild.Ref,
				&clients,
				internal.BuildNamespace,
				principal.User,
				config.HarborRepository,
				config.Builder,
				config.BuildCleanup,
			)
		})

	// Handler for deleting a build
	api.DeleteHandler = operations.DeleteHandlerFunc(
		func(params operations.DeleteParams, principal *models.Principal) middleware.Responder {
			return internal.Delete(
				&clients,
				internal.BuildNamespace,
				params.ID,
				principal.User,
			)
		})

}
