replicas: 2

image:
  name: tools-harbor.wmcloud.org/toolforge/builds-api
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 100Mi
    cpu: 500m
  requests:
    memory: 100Mi
    cpu: 500m

api:
  failurePolicy: Fail
  secretName: builds-api-certs

nginx:
  image:
    repository: docker-registry.tools.wmflabs.org/nginx
    tag: latest
    pullpolicy: Always

certificates:
  apiGatewayCa:
    name: api-gateway-backend-ca
    kind: ClusterIssuer
    group: cert-manager.io

config:
  debug: false
  port: 8000
  harborRepository: tools-harbor.wmcloud.org
  okBuildsToKeep: 1
  failedBuildsToKeep: 2
